# for reference https://mosquitto.org/man/mosquitto-conf-5.html
listener 1883
allow_anonymous true
accept_protocol_versions 5
persistence true
persistence_location /mosquitto/data/
log_dest file /mosquitto/log/mosquitto.log