# it reads the data ingestion fro the data_source and forward to mqtt broker as topic
# mqtt/publisher.py

import time
import json
import paho.mqtt.client as mqtt
import sys
import os

# this line is necessary for the relative imports
# For more detail on how python imports the model, see https://docs.python.org/3/library/sys_path_init.html
# this add to the list from sys.path that is used for searching of module
# or export the current path of project(root of the project) to PYTHONPATH and this code can be removed.
sys.path.append(os.path.dirname(os.path.dirname(__file__)))

# replace this with the function that is used to generate the ndvi sensor data
# the data source can either be a csv file that will be generated by the script 
# or the algorithm that would generate the time series in certain interval
from data_source.script import generate_reading

client = mqtt.Client(client_id="publisher",callback_api_version=mqtt.CallbackAPIVersion.VERSION2)
# broker host,port
client.connect("localhost", 1883)
client.loop_start()

while True:
    reading = generate_reading()
    topic = "topic"
    client.publish(topic, json.dumps(reading))
    print(topic,json.dumps(reading))
    time.sleep(5)